### ISSUE TITLE
response status code does not match any response statuses defined for this endpoint in the swagger spec (status 404): {}

### ISSUE THREAD

**Issue by Outsiderj** [SpenserCai/sd-webui-discord#1]
When running the bot I get this error: response status code does not match any response statuses defined for this endpoint in the swagger spec (status 404): {}

The bot connects to discord, but all output from the bot says the same thing: response status code does not match any response statuses defined for this endpoint in the swagger spec (status 404): {}

I have another discord SD bot that uses API, and that bot works if I run it.

**Comment by SpenserCai** [comment]
you need install extension：
sd-webui-rembg
sd-webui-deoldify
sd-webui-segment-anything
sd-webui-roop
sd-webui-controlnet

**Comment by SpenserCai** [comment]
when bot staring need get some options from that extension's api

**Comment by ZeusLT** [comment]
sd-webui-roop has been discontinued and it can no longer be installed. Could it be replaced with https://github.com/Gourieff/sd-webui-reactor instead?

**Comment by SpenserCai** [comment]
you can put the inswapper_128.onnx model to stable-diffusion-webui/models/roop/
and you can find it on https://huggingface.co/thebiglaskowski/inswapper_128.onnx/tree/main
