### ISSUE TITLE
Feature request: Ability for admins to ban users from utilizing the bot

### ISSUE THREAD

**Issue by itzjuan612** [SpenserCai/sd-webui-discord#10]
Now that the admin role feature is usable in latest update, I thought of a neat idea that would help with fair usage of Stable Diffusion
It would be great if admins could ban users from using the bot in case they generate inappropriate stuff, by running a simple command. The banned users info would be stored in the user_center.db file, and they wouldnt be able to run any command.
If its a feature that could easily be implemented in the code, it'd be cool to see it in an upcoming update.
Great bot by the way. It's one of the best projects ive ever run in my personal Stable Diffusion server.

**Comment by SpenserCai** [comment]
Thank you for your suggestion. In fact, this has been planned for a long time.

**Comment by SpenserCai** [comment]
complete
