### ISSUE TITLE
Add Database support for user settings

### ISSUE THREAD

**Issue by WaGi-Coding** [SpenserCai/sd-webui-discord#2]
As discussed on discord, i'd really appreciate user settings, saved in a database:
From Sampler, Steps, over to maybe their own style presets they can then choose from & so on.

For the database, i personally would prefer MySQL, as it's the easiest, most popular & known one which is also powerful & other than SQLite, can handle concurrent access and is scalable with connection pools, etc.

As both options would basically use the same SQL statements (afaik), you could also offer a simple, or default set up SQLite database, so users who won't mess with setting up MySQL, or simply don't need the power it offers because their community is small, also can make use of the user settings feature.

But i think SQLite could be a bit of a headache because it's basically not async accessable.

People reading this "issue" can suggest settings they'd like to have savable.

Greetings from Vienna

**Comment by SpenserCai** [comment]
@WaGi-Coding 
I have completed the development of the basic functions of the user center and currently support two commands:
/register: Register yourself as a user (the/setting command can only be used after registration)
/setting: If there are parameters, the parameter values will be set. If the current parameters are not set

At the same time, I have updated the configuration file template: config.example.json, where you can configure whether to enable User Center. If not enabled, there will be no related commands for User Center appearing

If you have time, you can try testing it. I have used both MySQL and sqlite drivers, and I am not sure if it will work properly in a Windows environment. At least the cross compilation has passed.
