### ISSUE TITLE
Using Realistic Vision Model

### ISSUE THREAD

**Issue by tomanick** [SpenserCai/sd-webui-discord#31]
Is it possible to use the model weights of Realistic Vision V6.0 B1 in your sd-webui-discord?

**Realistic Vision V6.0 B1:**
[https://civitai.com/models/4201?modelVersionId=245598](https://civitai.com/models/4201?modelVersionId=245598)

**Comment by SpenserCai** [comment]
download model to sd_webui's model dir,then you can use it
