### ISSUE TITLE
HTTP 400 Bad request when running /setting_ui

### ISSUE THREAD

**Issue by itzjuan612** [SpenserCai/sd-webui-discord#6]
Every time i run /setting_ui, the command doesn't work, and in log, this shows up.
Any fix i could try for myself? Or is it a bug? Please look into it. Thank you.

`2023/09/22 23:12:54 HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"components": {"0": {"components": {"0": {"options": {"_errors": [{"code": "BASE_TYPE_REQUIRED", "message": "This field is required"}]}}}}, "2": {"components": {"0": {"options": {"_errors": [{"code": "BASE_TYPE_REQUIRED", "message": "This field is required"}]}}}}}}}`

**Comment by itzjuan612** [comment]
Nevermind, it was a problem on my end.

**Comment by SpenserCai** [comment]
s this because you don't have any SD models
