### ISSUE TITLE
response status code does not match any response statuses defined for this endpoint in the swagger spec (status 404): {} 

### ISSUE THREAD

**Issue by aryan0078** [SpenserCai/sd-webui-discord#7]
While running txt2img command

![image](https://github.com/SpenserCai/sd-webui-discord/assets/44253539/263fa1a9-c32e-4830-a3c7-78c4c7140a49)

**Comment by aryan0078** [comment]
![image](https://github.com/SpenserCai/sd-webui-discord/assets/44253539/e35b2546-ab56-4b18-bb89-c9cbefcacdb7)

**Comment by SpenserCai** [comment]
are you use start command arg: --api?

**Comment by SpenserCai** [comment]
you can check with view:"http://127.0.0.1:7860/docs"

**Comment by aryan0078** [comment]
No my args are only --lowvram

**Comment by aryan0078** [comment]
> you can check with view:"http://127.0.0.1:7860/docs"

some commands are working some are not

**Comment by aryan0078** [comment]
Working now just have to add --api in webui-user.bat as argument
Thanks btw
