### ISSUE TITLE
reset api shutdowns the bot after text2img prompt

### ISSUE THREAD

**Issue by aryan0078** [SpenserCai/sd-webui-discord#8]
![image](https://github.com/SpenserCai/sd-webui-discord/assets/44253539/8c8e2f0c-4558-4b1b-8555-8d1afe22c51d)
![image](https://github.com/SpenserCai/sd-webui-discord/assets/44253539/d0f488c3-ee1d-4c8c-bf69-becfe389d683)

**Comment by SpenserCai** [comment]
Are you run on sd-Wendi v1.6.0?
And if bot be shutdown send output here

**Comment by SpenserCai** [comment]
After running, it will take some time to upload to Discord. Also ensure that 'sd webui'>=1.6.0
